cc_library(
	name="dessert",
	hdrs = [
		"include/dessert.h",
	],
	srcs= [
		"src/american_dessert.h",
		"src/brazilian_dessert.h",
		"src/italian_dessert.h",
	],
	visibility=["//visibility:public"],
)
