cc_library(
	name="main_course",
	hdrs = [
		"include/main_course.h",
	],
	srcs = [
		"src/american_main_course.h",
		"src/brazilian_main_course.h",
		"src/italian_main_course.h",
		"src/main_course.cc",
	],
	visibility=["//visibility:public"],
	copts=["-Isrc/main_course/include"],
)
