cc_library(
	name="main_course",
	hdrs=["american_main_course.h", "brazilian_main_course.h", "italian_main_course.h"],
	deps=["//include/interfaces:interfaces"],
	visibility=["//visibility:public"],
)
