cc_library(
	name="factories",
	hdrs=["american_meal_factory.h", "brazilian_meal_factory.h", "italian_meal_factory.h"],
	deps=[
		"//include/interfaces:interfaces",
		"//src/main_course:main_course",
		"//src/dessert:dessert",
	],
	visibility=["//visibility:public"],
)
