cc_library(
	name="factories",
	hdrs = [
		"include/meal_factory.h",
	],
	srcs = [
		"src/american_meal_factory.h",
		"src/brazilian_meal_factory.h",
		"src/italian_meal_factory.h",
	],
	deps=[
		"//main_course",
		"//dessert",
	],
	visibility=["//visibility:public"],
)
